# Generated by Django 3.2.5 on 2021-07-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=2000, unique=True)),
                ('ideology', models.CharField(choices=[('LW', 'Left Wing'), ('RW', 'Right Wing')], max_length=10)),
                ('image_url', models.TextField()),
                ('published_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
